DROP TABLE IF EXISTS msg;

CREATE TABLE msg (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  ip TEXT NOT NULL,
  hostname TEXT NOT NULL,
  arrival TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  body TEXT NOT NULL
);

